export const rapidApiKey = "USE YOUR OWN RAPID API KEY";

export const sliderImages = [
  require("../assets/images/slide1.png"),
  require("../assets/images/slide2.png"),
  require("../assets/images/slide3.png"),
  require("../assets/images/slide4.png"),
];

export const bodyParts = [
  {
    name: "back",
    image: require("../assets/images/back.png"),
  },
  {
    name: "cardio",
    image: require("../assets/images/cardio.png"),
  },
  {
    name: "lower arms",
    image: require("../assets/images/lowerArms.png"),
  },
  {
    name: "lower legs",
    image: require("../assets/images/lowerLegs.png"),
  },
  {
    name: "chest",
    image: require("../assets/images/chest.png"),
  },
  {
    name: "neck",
    image: require("../assets/images/neck.png"),
  },
  {
    name: "shoulders",
    image: require("../assets/images/shoulders.png"),
  },
  {
    name: "upper arms",
    image: require("../assets/images/upperArms.png"),
  },
  {
    name: "upper legs",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "waist",
    image: require("../assets/images/waist.png"),
  },
];

export const demoExercices = [
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/UtH4gyAzX7vWsJ",
    id: "0501",
    instructions: [
      "Start in a standing position with your feet shoulder-width apart.",
      "Lower your body into a squat position, placing your hands on the ground in front of you.",
      "Kick your feet back, landing in a push-up position.",
      "Perform a push-up, lowering your chest to the ground and then pushing back up.",
      "Jump your feet forward, landing in a squat position.",
      "Jump up explosively, reaching your arms overhead.",
      "Land softly and immediately lower back into the squat position to begin the next repetition.",
    ],
    name: "jack burpee",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "triceps",
      "core",
    ],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/LLNmA9fkc-oVix",
    id: "0630",
    instructions: [
      "Start in a high plank position with your hands directly under your shoulders and your body in a straight line.",
      "Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.",
      "Continue alternating legs in a running motion, keeping your hips low and your core engaged.",
      "Maintain a steady pace and breathe evenly throughout the exercise.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "mountain climber",
    secondaryMuscles: ["core", "shoulders", "triceps"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/F4qA3RwDDmNDpM",
    id: "0684",
    instructions: [
      "Start by standing upright with your feet hip-width apart.",
      "Engage your core and keep your upper body relaxed.",
      "Begin jogging in place, lifting your knees up towards your chest and landing softly on the balls of your feet.",
      "Maintain a steady pace and continue jogging for the desired duration or distance.",
      "Remember to breathe deeply and maintain good posture throughout the exercise.",
    ],
    name: "run (equipment)",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/bP0V1qP4brzyUJ",
    id: "0685",
    instructions: [
      "Start by standing upright with your feet hip-width apart.",
      "Engage your core and keep your upper body relaxed.",
      "Begin jogging in place, lifting your knees up towards your chest and landing softly on the balls of your feet.",
      "Maintain a steady pace and continue jogging for the desired duration or distance.",
      "Remember to breathe deeply and maintain good posture throughout the exercise.",
    ],
    name: "run",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "leverage machine",
    gifUrl: "https://v2.exercisedb.io/image/mlwteQsNp0ZmlL",
    id: "0798",
    instructions: [
      "Adjust the seat height and position on the stationary bike to ensure proper alignment.",
      "Place your feet on the pedals and secure them with the straps if available.",
      "Start pedaling at a comfortable pace, keeping your back straight and core engaged.",
      "Maintain a steady rhythm and increase the resistance level if desired.",
      "Continue pedaling for the desired duration of your cardio workout.",
      "Cool down by gradually reducing your pace and resistance level.",
      "Stretch your leg muscles after the workout to prevent tightness and promote recovery.",
    ],
    name: "stationary bike walk",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "body weight",
    gifUrl: "https://v2.exercisedb.io/image/ODuJefMm2RvsK1",
    id: "1160",
    instructions: [
      "Start in a standing position with your feet shoulder-width apart.",
      "Lower your body into a squat position by bending your knees and placing your hands on the floor in front of you.",
      "Kick your feet back into a push-up position.",
      "Perform a push-up, keeping your body in a straight line.",
      "Jump your feet back into the squat position.",
      "Jump up explosively, reaching your arms overhead.",
      "Land softly and immediately lower back into a squat position to begin the next repetition.",
    ],
    name: "burpee",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "chest",
    ],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "dumbbell",
    gifUrl: "https://v2.exercisedb.io/image/iN1QGOPUnMRjil",
    id: "1201",
    instructions: [
      "Start in a standing position with your feet shoulder-width apart and a dumbbell in each hand.",
      "Lower your body into a squat position, placing the dumbbells on the ground in front of you.",
      "Kick your feet back into a push-up position, keeping your body in a straight line.",
      "Perform a push-up, bending your elbows and lowering your chest towards the ground.",
      "Jump your feet back towards your hands, landing in a squat position.",
      "Stand up explosively, lifting the dumbbells off the ground and bringing them to your shoulders.",
      "Press the dumbbells overhead, fully extending your arms.",
      "Lower the dumbbells back to your shoulders and repeat the entire sequence for the desired number of repetitions.",
    ],
    name: "dumbbell burpee",
    secondaryMuscles: [
      "quadriceps",
      "hamstrings",
      "calves",
      "shoulders",
      "triceps",
      "core",
    ],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "stationary bike",
    gifUrl: "https://v2.exercisedb.io/image/OW6bfl8ZY9CiMq",
    id: "2138",
    instructions: [
      "Adjust the seat height and position to ensure proper alignment.",
      "Place your feet on the pedals and secure them with the straps if available.",
      "Start pedaling at a comfortable pace.",
      "Maintain a steady rhythm and increase the resistance as desired.",
      "Engage your core muscles to maintain stability and proper posture.",
      "Continue pedaling for the desired duration of your workout.",
      "Gradually decrease the resistance and slow down before coming to a complete stop.",
      "Stretch your legs and cool down after the workout.",
    ],
    name: "stationary bike run v. 3",
    secondaryMuscles: ["quadriceps", "hamstrings", "calves"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "elliptical machine",
    gifUrl: "https://v2.exercisedb.io/image/gCl9qIq6j09wd8",
    id: "2141",
    instructions: [
      "Adjust the resistance level and incline of the elliptical machine to your desired settings.",
      "Step onto the pedals of the machine and grip the handles lightly.",
      "Begin by pushing down with your feet and pulling the handles towards your body.",
      "Continue this motion, alternating between pushing and pulling, to simulate a walking or running motion.",
      "Maintain a steady pace and keep your core engaged throughout the exercise.",
      "Continue for the desired duration of your cardio workout.",
      "Gradually decrease the intensity and speed of the machine before stepping off.",
    ],
    name: "walk elliptical cross trainer",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    target: "cardiovascular system",
  },
  {
    bodyPart: "cardio",
    equipment: "stepmill machine",
    gifUrl: "https://v2.exercisedb.io/image/5VF2f9jDgBdbty",
    id: "2311",
    instructions: [
      "Adjust the stepmill machine to a comfortable level.",
      "Step onto the machine and place your hands on the handrails for support.",
      "Start walking by placing one foot on a step and then the other, alternating between legs.",
      "Maintain an upright posture and engage your core muscles.",
      "Continue walking for the desired duration or distance.",
      "Gradually increase the intensity or speed as you become more comfortable with the exercise.",
      "Remember to cool down and stretch after completing the exercise.",
    ],
    name: "walking on stepmill",
    secondaryMuscles: ["quadriceps", "hamstrings", "glutes", "calves"],
    target: "cardiovascular system",
  },
];
